server:
  port: 8083

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/imform
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
jwt:
  secret: "c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0"

logging:
  level:
    org.hibernage.SQL: debug
    org:
      hibernage:
        type: trace
